language: php

## Cache composer bits
cache:
  directories:
    - $HOME/.composer/cache/files

## Build matrix for lowest and highest possible targets
matrix:
  include:
    - php: 7.2
      env:
        - qaExtended=true
    - os: osx
      osx_image: xcode10.1
      language: generic
      env:
        - qaExtended=true
        - _OSX=10.13
        - _PHP: php72
    - php: 7.3
    - php: nightly
      env:
        - dropPlatform=false
    - php: 7.2
      env:
        - dependencies=lowest
    - php: 7.3
      env:
        - dependencies=lowest
    - php: nightly
      env:
        - dependencies=lowest
        - dropPlatform=false
    - php: 7.2
      env:
        - dependencies=highest
    - os: osx
      osx_image: xcode10.1
      language: generic
      env:
        - dependencies=highest
        - _OSX=10.13
        - _PHP: php72
    - php: 7.3
      env:
        - dependencies=highest
    - php: nightly
      env:
        - dependencies=highest
        - dropPlatform=false

before_install:
  - if [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then /usr/bin/env bash build/prepare_osx_env.sh ; fi

## Install or update dependencies
install:
  - if [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then /usr/bin/env bash build/handle_brew_pkg.sh php ; fi
  - if [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then /usr/bin/env bash build/handle_brew_pkg.sh composer ; fi
  - composer validate
  - if [ -z "$dropPlatform" ]; then composer config --unset platform.php; fi;
  - if [ -z "$qaExtended" ]; then phpenv config-rm xdebug.ini || :; fi;
  - if [ -z "$dependencies" ]; then composer install --prefer-dist; fi;
  - if [ "$dependencies" = "lowest" ]; then composer update --prefer-lowest --prefer-dist -n; fi;
  - if [ "$dependencies" = "highest" ]; then composer update --prefer-dist -n; fi;
  - composer show

## Run the actual test
script:
  - if [ -z "$qaExtended" ]; then make ci; fi;
  - if [ "$qaExtended" = "true" ]; then make ci-extended; fi;

## Gather coverage and set it to coverage servers
after_script: if [ "$qaExtended" = "true" ]; then make ci-coverage; fi;
